[preferences]
user="letder"
terminal = "kitty"
browser = "firefox"
wallpaper = 12         # number -> will search ^wallpaper${number}\.* in ../wallpapers; if string -> absolute path to wallpaper image
neovim = true         # Clones and setup this config https://github.com/Letder40/nvim-config/
animations = true     # boolean setup picom

# The following packages will be installed on setup accepts an array of strings with valid software names instalable with pacman
# Change as much as you want

[packages]
# will be installed and auto started
init = [
    { exec="fcitx5 -d", package="fcitx5" },
    { exec="volumeicon", package="volumeicon" },
    { exec="udiskie --appindicator", package="udiskie" },
    { exec="blueman-applet", package="blueman" },
    { exec="nm-applet", package="network-manager-applet" },
    { exec="setxkbmap es", package="" },
]

others = [
    "discord",
    "bitwarden",
    "notion",
    "zathura",
] 
