#!/bin/bash
ip=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $1}' FS=/ )
mask=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $2}' FS=/ )

echo $ip 
echo $mask

octeto1=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $1}' FS=/ | awk '{print $1}' FS=. )
octeto2=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $1}' FS=/ | awk '{print $2}' FS=. )
octeto3=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $1}' FS=/ | awk '{print $3}' FS=. )
octeto4=$( ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1  | awk '{print $1}' FS=/ | awk '{print $4}' FS=. )

echo $octeto4
