#!/bin/bash
if [[ $1 == "-i24" && $2 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
   o1_3=$(echo $2 | cut -d "." -f 1,2,3 )
   for o4 in $(seq 1 254); do
      timeout 1 bash -c "ping $o1_3.$o4 -c1" > /dev/null && echo "host $o1_3.$o4 is up" &
   done; wait
   exit 0
fi

if [[ $1 == "-i16" && $2 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
   o1_2=$(echo $2 | cut -d "." -f 1,2 )
   for o3 in $(seq 1 254); do
      for o4 in $(seq 1 254); do
          timeout 1 bash -c "ping $o1_2.$o3.$o4 -c1" > /dev/null && echo "host $o1_2.$o3.$o4 is up" &
      done
   done; wait  
fi
#MANUAL
##############


##############
#AUTO

get_ip=$( ip a | grep -oP "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/24") && obtenida=true
firstsocts=$( echo $get_ip | cut -d "." -f 1,2,3 )

if [ $obtenida != true ]; then
   
   #comprobar si verdadadero
   echo -e "We can't get the ip range automatly, you are probably in a net with a submask different to /24 \nif you are sure that you are in a net with submask /24 use -i24 to sepecify any ip on /24, -i16 any ip on /16, -i8 any ip on /8"
   exit 1

else
   #auto
   for finaloct in $(seq 1 254); do
      timeout 1 bash -c "ping $firstsocts.$finaloct -c1" > /dev/null && echo "host $firstsocts.$finaloct is up" &
   done; wait
   exit 0
fi
