#!/bin/bash
if [[ $1 == "-sd" ]]; then
   scp -rp letder@192.168.1.10:/home/letder/workspace/dev/scripts/* $2 
   exit 0
elif [[ $1 == "-r" && $2 == "-sd" ]]; then
   scp -rp -P 64500 letder@178.60.68.186:/home/letder/workspace/dev/scripts/* $3 
   exit 0
fi


if [[ $1 == "-r" ]]; then
   scp -rp -P 64500 letder@178.60.68.186:/home/letder/workspace/dev/scripts/* ~/scripts 
   exit 0
else
   scp -rp letder@192.168.1.10:/home/letder/workspace/dev/scripts/* ~/scripts
   exit 0
fi

