#!/bin/bash
if [[ $1 == "H" ]]; then
   xrandr --output DP-2 --primary --mode 1920x1080 --pos 1920x0 --output DP-0 --mode 1920x1080 --pos 0x0 
elif [[ $1 == "V" ]]; then
   xrandr --output DP-2 --primary --mode 1920x1080 --pos 0x1080 --output DP-0 --mode 1920x1080 --pos 0x0
elif [[ $1 == "PCIonly" ]]; then
   xrandr --output DP-2 --primary --mode 1920x1080 --output DP-0 --mode 0x0
elif [[ $1 == "HDMIonly" ]]; then
   xrandr --output DP-2 --mode 0x0 --output DP-0 --mode 1920x1080 --primary
elif [[ $1 == "mirror" ]]; then
   xrandr --output DP-2 --mode 1920x1080 --primary --pos 0x0 --output DP-0 --mode 1920x1080 --pos 0x0
else 
   echo "that option isn't contemplated in this script" 
fi


