ZSH_CONFIG_DIR="${${${(%):-%x}:A}:h}/config"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Path ###
source "$ZSH_CONFIG_DIR/path.zsh"

### OMZ ###
source "$ZSH_CONFIG_DIR/omz.zsh"
source "$ZSH/oh-my-zsh.sh"

# To customize the prompt, run `p10k configure` or edit the sourced file below.
source "$ZSH_CONFIG_DIR/p10k.zsh"

### FUNCTIONS ###
source "$ZSH_CONFIG_DIR/functions.zsh"

### ALIAS ###
source "$ZSH_CONFIG_DIR/aliases.zsh"

### KEYMAPS ###
command -v nvim &>/dev/null && bindkey -v

### TOOLS SETUP ###
source "$ZSH_CONFIG_DIR/tools.zsh"

# User configuration
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="nvim"
export VISUAL="$EDITOR"
export LANG=es_ES.UTF-8
# Compilation flags
# export ARCHFLAGS="-arch x86_64"
