# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path
export PATH=$PATH:$HOME/bins:/usr/local/bin:$HOME/.local/bin:
[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"

# ohmyzsh
[[ -d "$HOME/.oh-my-zsh" ]] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
export ZSH="$HOME/.oh-my-zsh"

zstyle ':omz:update' mode auto  # update automatically without asking

CASE_SENSITIVE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

# Plugins
[[ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]] || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting &>/dev/null

plugins=(
	git
	zsh-syntax-highlighting
)

# p10k
[[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" &>/dev/null

ZSH_THEME="powerlevel10k/powerlevel10k"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="nvim"
export LANG=es_ES.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

### ALIAS ###

alias zathura-dark="zathura -c ~/.config/zathura/zathura-darkrc"
alias pdf="zathura"
alias ip="ip -c"
alias cat="bat"
alias off="shutdown now"
alias camen="sudo modprobe -r uvcvideo"
alias vpn="sudo openvpn --config /etc/openvpn/client/nl-free-140090.protonvpn.udp.ovpn"
alias neofetch="fastfetch"
alias spt="spotify_player"
alias lorien="/opt/Lorien_v0.6.0_Linux/Lorien.x86_64"
alias vi="nvim"
alias vim="nvim"
alias icat="kitten icat"

############

# EZA #

alias ls='eza --icons --color=always --group-directories-first'
alias ll='eza -lM@O --color=always --git --icons --group-directories-first --time-style long-iso'
alias lla='eza -lM@Oa --color=always --git --icons --group-directories-first --time-style long-iso'
alias la='eza -a --icons --color=always -g --group-directories-first'
alias l.='eza -a | egrep "^\."'

# FZF
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git --exclude node_modules'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="
  --height 45% 
  --layout=reverse 
  --border 
  --info=inline 
  --color=dark
  --color=fg:-1,bg:-1,hl:#c678dd,fg+:#ffffff,bg+:#4b5263,hl+:#c678dd
  --color=info:#98c379,prompt:#61afef,pointer:#be5046,marker:#e5c07b,header:#61afef
"
source <(fzf --zsh)

bindkey -r '^T'
bindkey '\ef' fzf-file-widget
bindkey '\ec' fzf-cd-widget

# VIM mode
bindkey -v

# Fuck
eval $(thefuck --alias)

# Zoxide
eval "$(zoxide init --cmd cd zsh)"

# Pyenv
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init - zsh)"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
