# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Path ###
export PATH=$PATH:$HOME/bins:/usr/local/bin:$HOME/.local/bin
[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"

### oh-my-zsh ###
export ZSH="$HOME/.oh-my-zsh"

zstyle ':omz:update' mode auto  # update automatically without asking

CASE_SENSITIVE="false"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="false"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

# Plugins
plugins=(
	git
	zsh-syntax-highlighting
)

# User configuration
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="nvim"
export LANG=es_ES.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# p10k
ZSH_THEME="powerlevel10k/powerlevel10k"

# must be at the bottom of ohmyzsh and theme config
source "$ZSH/oh-my-zsh.sh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

### ALIAS ###

alias_if_command() {
    local name="$1"
    local command="$2"
    local target="${3:-$2}"

    command -v "$command" &>/dev/null && alias "$name=$target"
}

alias_if_executable() {
    local name="$1"
    local path="$2"
    local target="${3:-$2}"

    [[ -x "$path" ]] && alias "$name=$target"
}

alias_if_command zathura-dark zathura "zathura -c ~/.config/zathura/zathura-darkrc"
alias_if_command pdf zathura
alias_if_command cat bat
alias_if_command neofetch fastfetch
alias_if_command spt spotify_player
alias_if_command vi nvim
alias_if_command vim nvim
alias_if_command icat kitten "kitten icat"

alias_if_executable lorien "/opt/Lorien_v0.6.0_Linux/Lorien.x86_64"

alias ip="ip -c"
alias off="shutdown now"

### EZA ###

alias ls='eza --icons --color=always --group-directories-first'
alias ll='eza -lM@O --color=always --git --icons --group-directories-first --time-style long-iso'
alias lla='eza -lM@Oa --color=always --git --icons --group-directories-first --time-style long-iso'
alias la='eza -a --icons --color=always -g --group-directories-first'
alias l.='eza -a | egrep "^\."'

### KEYMAPS ###

bindkey -v

bindkey -r '^T'
bindkey '\ef' fzf-file-widget
bindkey '\ec' fzf-cd-widget
bindkey '\eh' fzf-history-widget

### TOOLS SETUP ###

# fzf
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git --exclude node_modules'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="
  --height 45% 
  --layout=reverse 
  --border 
  --info=inline 
  --color=dark
  --color=fg:-1,bg:-1,hl:#c678dd,fg+:#ffffff,bg+:#4b5263,hl+:#c678dd
  --color=info:#98c379,prompt:#61afef,pointer:#be5046,marker:#e5c07b,header:#61afef
"
source <(fzf --zsh)

# Fuck
eval $(thefuck --alias)

# Zoxide
eval "$(zoxide init --cmd cd zsh)"

# Pyenv
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init - zsh)"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

# bun completions
[[ -s "$HOME/.bun/_bun" ]] && source "$HOME/.bun/_bun"
[[ -d "$HOME/.bun/bin" ]] && export PATH="$PATH:$HOME/.bun/bin"
